### PR TITLE
LOG=true

### PR DESCRIPTION
**Pull request by orangewise**
Added flag to enable logging. Logging is disabled by default.

### CODE REVIEW

**Comment by DanielDornhardt** [comment]
Hi, thanks!

But actually, I'm not that hot that per default the package wouldn't log... my command line is already overflowing with environment variables...

I would prefer to make _disabling_ the logging an option.

Basically my yagni:log - package wasn't designed as a real logging tool, more for quick debug-style logging - and that's why i would like to keep logging on by default.

Thanks for catching the mrt/meteor mistake in the docs, i'll update that...

I'll think about supporting disabling logging in the package, but right now am not sure I need it / want it in the package as it is.

If you'd add disabling the logging instead of enabling it i'd keep it.

Also I'd prefer it to not to have to make a call to the server every time log() is called - probably getting the info once would be enough and then save it in a variable somewhere?

Also Pt. II: I feel letting the package user call a function / set a variable in his own code to enable / disable the logging would be good too - then developers could add it to the public - part of their settings and then call enable / disable from their code. Then we wouldn't need the call to the server either and we could keep the environment vars clean as well...

Anyways, I'm not merging it as it is, but I thank you for your time and I hope your fork will be very helpful to you!

Thank you again and best wishes

Daniel

**Comment by orangewise** [comment]
hi Daniel, I think you are right about the server call. That is not so pretty :)

Anyway, I created a new smart package that serves my needs better. It is basically a wrapper for npm debug. You can find it here: https://atmospherejs.com/robodo/meteor-debug

Regards,
Ronald

**Comment by DanielDornhardt** [comment]
Hey Ronald,

good to see that you found a good solution for yourself.

A quick question:

With

var d = debugs('orangewise');
d('server side debug');
- is that on the client side and the messages will be passed on to the
  server? Will they be logged on both sides?

The Documentation isn't a 100% clear to me.

But the server side log coloring _does_ look pretty fancy! :D

Thanks and best wishes

Daniel

Daniel Dornhardt, Daniel Dornhardt Development
daniel@dornhardt.com
+49 152 - 56 17 22 61

**Comment by orangewise** [comment]
Hi Daniel, 

I updated the package. There is not need to use the 'debugs' function any more. This works both on the server and the client:

var d = debugs('orangewise');
d('client or server side debug');

Messages will not be passed on from the client to the server. Server messages are displayed on the server, client messages are displayed in the browser. Just as described in the the readme of npm debug.

Hope this clarifies it a little.

Take care,
Ronald

**Comment by DanielDornhardt** [comment]
Hi, very nice!

Thank you for keeping me posted! :)

See you around :)

Daniel Dornhardt, Daniel Dornhardt Development
daniel@dornhardt.com
+49 152 - 56 17 22 61

**Pull request closed without merging**
